name: Build image on merge

on:
  pull_request:
    types: [closed, labeled]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --tag adriarr .
