name: Build and publish image on release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push the Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ env.REPOSITORY_NAME }}
          VERSION=${{ github.event.release.tag_name }}

          docker build --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:latest .
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
